name: geomag
description: (fork) Translate GPS location data to geo-magnetic data such as magnetic declination.

publish_to: 'none'

version: 0.2.1
homepage: https://github.com/jifalops/geomag

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl:

dev_dependencies:
  flutter_lints: ^3.0.1
  test: ^1.6.5